language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install: composer validate --strict

install: composer install

script: composer run-behat

cache:
  directories:
    - vendor

notifications:
  email:
    on_success: never
    on_failure: change
