language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - WP_CLI_TEST_DBUSER=travis
    - WP_CLI_TEST_DBPASS=

before_install: composer validate --strict

install: composer install

script: composer run-behat

cache:
  directories:
    - vendor

notifications:
  email:
    on_success: never
    on_failure: change
